# Generated by debtap
# Maintainer: Kure Fukumakoto <kure.fukumakoto@gmail.com>
# Contributor: Xiezuo Team <xiezuo@wps.cn>
pkgname=xiezuo-bin
pkgver=5.14.0
pkgrel=1
pkgdesc="WPS一站式企业沟通与协作平台. 整合即时沟通、文档协作、精选应用功能于一体，让办公更高效、更愉悦"
arch=('x86_64' 'aarch64')
url="https://xz.wps.cn/"
license=('unknown')
depends=('gtk3' 'libnotify' 'nss' 'libxss' 'libxtst' 'xdg-utils' 'at-spi2-core' 'util-linux-libs' 'libsecret')
optdepends=('libappindicator-gtk3')
conflicts=('xiezuo')
provides=('kingsoft-xiezuo' 'xiezuo')
options=('!strip' '!emptydirs')
install=${pkgname}.install
source_x86_64=("xiezuo-linux-x64-stable-${pkgver}.deb::https://woa.wps.cn/download/deb-X64")
source_aarch64=("xiezuo-linux-arm64-stable-${pkgver}.deb::https://woa.wps.cn/download/deb-Arm64")
sha256sums_x86_64=('a8bab210ddb14ce1a655bdd0bca3030513b05f66f30f0dbdcc9e72cdb0322616')
sha256sums_aarch64=('845d0c915224f44ac85b8950cd720dc3eae1e42648d88f710c86c0cad273971d')


package(){
  # Extract package data
  tar xpvf "${srcdir}/data.tar.xz" --xattrs-include='*' --numeric-owner -C "${pkgdir}"

  # Modify files
  cd "${pkgdir}"
  mv "${pkgdir}"/usr/share/doc/{kingsoft-xiezuo,xiezuo}

  # Fix directory permissions
  find "${pkgdir}" -type d | xargs chmod 755
}
